set-option -g prefix C-a
bind-key a send-prefix

new-session -A

set -g status-right '#{USER}@#H'
set -g status-left ''

set -g history-limit 99999

bind h split-window -h
bind v split-window -v


# Ativa o suporte ao mouse e o modo vi
set -g mouse on
set-window-option -g mode-keys vi
set -g set-clipboard on

# Ao arrastar o mouse, seleciona o texto visualmente
unbind-key -T copy-mode-vi MouseDragEnd1Pane

# Comportamento do botão do meio:
#   Se houver texto selecionado, copia para o clipboard do Wayland.
#   Se não houver, cola o conteúdo do clipboard.
unbind-key MouseDown2Pane
bind-key -T root MouseDown2Pane \
    if-shell "tmux send-keys -X copy-selection" \
    "send-keys -X copy-pipe-and-cancel 'wl-copy -p'" \
    "paste-buffer"
