set-option -g prefix C-a
bind-key a send-prefix

new-session -n $HOST

set -g mouse on
set -g history-limit 10000

unbind %

bind s split-window -v
bind v split-window -h

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

set -g status-right '#{USER}@#H'
set -g status-left ''

set -g set-clipboard on
set -s copy-command 'xsel -i'
set -as terminal-features ',rxvt-unicode-256color:clipboard'


set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'
